Split out commonly used functions into bin/lib, update all convenience scripts with new online check function

diff --git a/bin/angel2barstool b/bin/angel2barstool
--- a/bin/angel2barstool
+++ b/bin/angel2barstool
@@ -32,12 +32,14 @@ if [ "$1" == "-l" ]; then
   botctrl -a sit -n Angel -u slstool
 else
   # Check if online
-  botctrl -a status -c Easy | grep 'Angelus Portal' >/dev/null || {
-    # Maybe Easy is not online
-    botctrl -a status -c Angel | grep 'Angelus Portal' >/dev/null || {
-      echo "Angelus Portal does not appear to be online"
-      exit 1
-    }
+  [ -f /usr/local/BotControl/lib/online ] || {
+    echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+    exit 1
+  }
+  source /usr/local/BotControl/lib/online
+  co_bot_online Angel || {
+    echo "Angelus Portal does not appear to be online"
+    exit 1
   }
 
   botctrl -a stand -c Angel >/dev/null 2>&1
diff --git a/bin/bot2dj b/bin/bot2dj
--- a/bin/bot2dj
+++ b/bin/bot2dj
@@ -78,11 +78,14 @@ case "${BOT}" in
     ;;
   Angel*|angel*)
     # Check if online
-    botctrl -a status -c Easy | grep Angel >/dev/null || {
-      botctrl -a status -c Angel | grep Angel >/dev/null || {
-        echo "Angelus does not appear to be online"
-        exit 1
-      }
+    [ -f /usr/local/BotControl/lib/online ] || {
+      echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+      exit 1
+    }
+    source /usr/local/BotControl/lib/online
+    co_bot_online Angel || {
+      echo "Angelus Portal does not appear to be online"
+      exit 1
     }
     botctrl -a stand -c Angel >/dev/null 2>&1
     sleep 1
@@ -92,11 +95,14 @@ case "${BOT}" in
     ;;
   Easy*|easy*)
     # Check if online
-    botctrl -a status -c Angel | grep Easy >/dev/null || {
-      botctrl -a status -c Easy | grep Easy >/dev/null || {
-        echo "Easy does not appear to be online"
-        exit 1
-      }
+    [ -f /usr/local/BotControl/lib/online ] || {
+      echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+      exit 1
+    }
+    source /usr/local/BotControl/lib/online
+    co_bot_online Easy || {
+      echo "Easy Islay does not appear to be online"
+      exit 1
     }
     botctrl -a stand -c Easy >/dev/null 2>&1
     sleep 1
diff --git a/bin/bots2bpool b/bin/bots2bpool
--- a/bin/bots2bpool
+++ b/bin/bots2bpool
@@ -30,17 +30,26 @@ do
 done
 [ "${needsleep}" ] && sleep 10
 
+# Send Anya to the beach pool float
+botctrl -a teleport -n Anya -l beach
+sleep 5
+botctrl -a sit -n Anya -u bfloat
+
 # Send Angelus and Easy to the beach pool
 for bot in Easy Angel
 do
+  [ -f /usr/local/BotControl/lib/online ] || {
+    echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+    exit 1
+  }
+  source /usr/local/BotControl/lib/online
+  co_bot_online ${bot} || {
+    echo "${bot} does not appear to be online"
+    continue
+  }
   botctrl -a stand -c ${bot} >/dev/null 2>&1
   sleep 1
   botctrl -a teleport -c ${bot} -l beach >/dev/null 2>&1
   sleep 5
   botctrl -a sit -c ${bot} -u bpool
 done
-
-# Send Anya to the beach pool float
-botctrl -a teleport -n Anya -l beach
-sleep 5
-botctrl -a sit -n Anya -u bfloat
diff --git a/bin/bots2clubdance b/bin/bots2clubdance
--- a/bin/bots2clubdance
+++ b/bin/bots2clubdance
@@ -66,16 +66,14 @@ done
 for bot in ${CBOTS}
 do
   # Check if online
-  if [ "${bot}" == "Angel" ]; then
-    use="Easy"
-  else
-    use="Angel"
-  fi
-  botctrl -a status -c ${use} | grep ${bot} >/dev/null || {
-    botctrl -a status -c ${bot} | grep ${bot} >/dev/null || {
-      echo "${bot} does not appear to be online"
-      continue
-    }
+  [ -f /usr/local/BotControl/lib/online ] || {
+    echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+    exit 1
+  }
+  source /usr/local/BotControl/lib/online
+  co_bot_online ${bot} || {
+    echo "${bot} does not appear to be online"
+    continue
   }
 
   botctrl -a stand -c ${bot} >/dev/null 2>&1
diff --git a/bin/checkstatus b/bin/checkstatus
--- a/bin/checkstatus
+++ b/bin/checkstatus
@@ -34,29 +34,11 @@ usage() {
   exit 1
 }
 
-check_co_bot() {
-  local slbot="$1"
-  # Check for Name alias in ~/.botctrl
-  local SL_NAME="${slbot}"
-  local botname=$(echo "${slbot}" | sed -e "s/ /_/g")
-  local envname="BOT_NAME_${botname}"
-  [ "${!envname}" ] && SL_NAME="${!envname}"
-  if botctrl -a status -c "${SL_NAME}" 2>&1 | grep 'parse error' >/dev/null; then
-    STATUS="OFFLINE"
-  else
-    STATUS="ONLINE"
-  fi
-  if [ "${have_jq}" ]; then
-    printf "\n{\n  \"action\": \"status\",\n  \"status\": \"${STATUS}\",\n  \"slname\": \"${SL_NAME}\"\n}\n" | jq -r .
-  else
-    printf '\n{'
-    printf '\n  "action": "status",'
-    printf "\n  \"status\": \"${STATUS}\","
-    printf "\n  \"slname\": \"${SL_NAME}\""
-    printf '\n}\n'
-  fi
-  sleep 2
+[ -f /usr/local/BotControl/lib/status ] || {
+  echo "ERROR: cannot locate /usr/local/BotControl/lib/status"
+  exit 1
 }
+source /usr/local/BotControl/lib/status
 
 BOT= allbots=1 corrade= lifebot=
 while getopts ":Acln:h" flag; do
diff --git a/bin/easy2pool b/bin/easy2pool
--- a/bin/easy2pool
+++ b/bin/easy2pool
@@ -35,12 +35,14 @@ if [ "$1" == "-l" ]; then
   botctrl -a sit -n Easy -u zlounger
 else
   # Check if online
-  botctrl -a status -c Angel | grep 'Easy Islay' >/dev/null || {
-    # Maybe Angel is not online
-    botctrl -a status -c Easy | grep 'Easy Islay' >/dev/null || {
-      echo "Easy Islay does not appear to be online"
-      exit 1
-    }
+  [ -f /usr/local/BotControl/lib/online ] || {
+    echo "ERROR: cannot locate /usr/local/BotControl/lib/online"
+    exit 1
+  }
+  source /usr/local/BotControl/lib/online
+  co_bot_online Easy || {
+    echo "Easy Islay does not appear to be online"
+    exit 1
   }
 
   # Send Easy to the right lounge chair
